import { DateTime } from 'luxon'
import { BaseSeeder } from '@adonisjs/lucid/seeders'
import UserRole from '#enums/user_role'
import VerificationStatus from '#enums/verification_status'
import User from '#models/user'
import ArtisanProfile from '#models/artisan_profile'

type ArtisanSeed = {
  firstName: string
  lastName: string
  email: string
  phoneNumber: string
  city: string
  state: string
  address: string
  businessName: string
  trade: string
  bio: string
  yearsOfExperience: number
  serviceRadiusKm: number
  nin: string
  bvn: string
  guarantorFullName: string
  guarantorEmail: string
  guarantorPhoneNumber: string
  guarantorCity: string
  guarantorState: string
  guarantorAddress: string
  verificationStatus: VerificationStatus
}

const PASSWORD = 'password123'

/**
 * 16 artisans: the first 8 are approved (verified), the last 8 are pending
 * verification. Data is deterministic so the seeder is idempotent when re-run.
 */
const ARTISANS: ArtisanSeed[] = [
  // ---------- Verified / approved (8) ----------
  {
    firstName: 'Chinedu',
    lastName: 'Okafor',
    email: 'chinedu.okafor@betawork.app',
    phoneNumber: '+2348030000001',
    city: 'Ikeja',
    state: 'Lagos',
    address: '12 Allen Avenue, Ikeja',
    businessName: 'Chinedu Electricals',
    trade: 'Electrician',
    bio: 'Certified electrician with a decade of residential and commercial wiring experience.',
    yearsOfExperience: 10,
    serviceRadiusKm: 25,
    nin: '10000000001',
    bvn: '20000000001',
    guarantorFullName: 'Emeka Okafor',
    guarantorEmail: 'emeka.okafor@example.com',
    guarantorPhoneNumber: '+2348090000001',
    guarantorCity: 'Ikeja',
    guarantorState: 'Lagos',
    guarantorAddress: '5 Opebi Road, Ikeja',
    verificationStatus: VerificationStatus.APPROVED,
  },
  {
    firstName: 'Aisha',
    lastName: 'Bello',
    email: 'aisha.bello@betawork.app',
    phoneNumber: '+2348030000002',
    city: 'Wuse',
    state: 'Abuja',
    address: '4 Aminu Kano Crescent, Wuse 2',
    businessName: 'Aisha Interiors',
    trade: 'Painter',
    bio: 'Interior and exterior painting specialist known for clean, durable finishes.',
    yearsOfExperience: 7,
    serviceRadiusKm: 30,
    nin: '10000000002',
    bvn: '20000000002',
    guarantorFullName: 'Fatima Bello',
    guarantorEmail: 'fatima.bello@example.com',
    guarantorPhoneNumber: '+2348090000002',
    guarantorCity: 'Wuse',
    guarantorState: 'Abuja',
    guarantorAddress: '10 Adetokunbo Ademola Crescent, Wuse 2',
    verificationStatus: VerificationStatus.APPROVED,
  },
  {
    firstName: 'Tunde',
    lastName: 'Adeyemi',
    email: 'tunde.adeyemi@betawork.app',
    phoneNumber: '+2348030000003',
    city: 'Ibadan',
    state: 'Oyo',
    address: '23 Ring Road, Ibadan',
    businessName: 'Adeyemi Plumbing Works',
    trade: 'Plumber',
    bio: 'Reliable plumber handling installations, repairs and drainage across Ibadan.',
    yearsOfExperience: 12,
    serviceRadiusKm: 40,
    nin: '10000000003',
    bvn: '20000000003',
    guarantorFullName: 'Bisi Adeyemi',
    guarantorEmail: 'bisi.adeyemi@example.com',
    guarantorPhoneNumber: '+2348090000003',
    guarantorCity: 'Ibadan',
    guarantorState: 'Oyo',
    guarantorAddress: '8 Bodija Estate, Ibadan',
    verificationStatus: VerificationStatus.APPROVED,
  },
  {
    firstName: 'Ngozi',
    lastName: 'Eze',
    email: 'ngozi.eze@betawork.app',
    phoneNumber: '+2348030000004',
    city: 'Enugu',
    state: 'Enugu',
    address: '17 Ogui Road, Enugu',
    businessName: 'Ngozi Tailoring House',
    trade: 'Tailor',
    bio: 'Bespoke fashion designer creating traditional and contemporary outfits.',
    yearsOfExperience: 9,
    serviceRadiusKm: 20,
    nin: '10000000004',
    bvn: '20000000004',
    guarantorFullName: 'Chidi Eze',
    guarantorEmail: 'chidi.eze@example.com',
    guarantorPhoneNumber: '+2348090000004',
    guarantorCity: 'Enugu',
    guarantorState: 'Enugu',
    guarantorAddress: '2 Independence Layout, Enugu',
    verificationStatus: VerificationStatus.APPROVED,
  },
  {
    firstName: 'Ibrahim',
    lastName: 'Musa',
    email: 'ibrahim.musa@betawork.app',
    phoneNumber: '+2348030000005',
    city: 'Kano',
    state: 'Kano',
    address: '30 Zoo Road, Kano',
    businessName: 'Musa Auto Care',
    trade: 'Mechanic',
    bio: 'Auto mechanic specialising in engine diagnostics and fleet maintenance.',
    yearsOfExperience: 15,
    serviceRadiusKm: 35,
    nin: '10000000005',
    bvn: '20000000005',
    guarantorFullName: 'Sani Musa',
    guarantorEmail: 'sani.musa@example.com',
    guarantorPhoneNumber: '+2348090000005',
    guarantorCity: 'Kano',
    guarantorState: 'Kano',
    guarantorAddress: '14 Bompai Road, Kano',
    verificationStatus: VerificationStatus.APPROVED,
  },
  {
    firstName: 'Funke',
    lastName: 'Ogunleye',
    email: 'funke.ogunleye@betawork.app',
    phoneNumber: '+2348030000006',
    city: 'Abeokuta',
    state: 'Ogun',
    address: '6 Kuto Road, Abeokuta',
    businessName: 'Funke Beauty Studio',
    trade: 'Hairstylist',
    bio: 'Professional hairstylist offering styling, braiding and salon training.',
    yearsOfExperience: 8,
    serviceRadiusKm: 15,
    nin: '10000000006',
    bvn: '20000000006',
    guarantorFullName: 'Yemi Ogunleye',
    guarantorEmail: 'yemi.ogunleye@example.com',
    guarantorPhoneNumber: '+2348090000006',
    guarantorCity: 'Abeokuta',
    guarantorState: 'Ogun',
    guarantorAddress: '21 Panseke, Abeokuta',
    verificationStatus: VerificationStatus.APPROVED,
  },
  {
    firstName: 'Emeka',
    lastName: 'Nwosu',
    email: 'emeka.nwosu@betawork.app',
    phoneNumber: '+2348030000007',
    city: 'Port Harcourt',
    state: 'Rivers',
    address: '9 Aba Road, Port Harcourt',
    businessName: 'Nwosu Woodworks',
    trade: 'Carpenter',
    bio: 'Furniture maker and finish carpenter with a focus on custom cabinetry.',
    yearsOfExperience: 11,
    serviceRadiusKm: 28,
    nin: '10000000007',
    bvn: '20000000007',
    guarantorFullName: 'Uche Nwosu',
    guarantorEmail: 'uche.nwosu@example.com',
    guarantorPhoneNumber: '+2348090000007',
    guarantorCity: 'Port Harcourt',
    guarantorState: 'Rivers',
    guarantorAddress: '3 Old GRA, Port Harcourt',
    verificationStatus: VerificationStatus.APPROVED,
  },
  {
    firstName: 'Halima',
    lastName: 'Yusuf',
    email: 'halima.yusuf@betawork.app',
    phoneNumber: '+2348030000008',
    city: 'Kaduna',
    state: 'Kaduna',
    address: '18 Ahmadu Bello Way, Kaduna',
    businessName: 'Halima Tiling & Masonry',
    trade: 'Tiler',
    bio: 'Skilled tiler and mason delivering precise floor and wall installations.',
    yearsOfExperience: 6,
    serviceRadiusKm: 22,
    nin: '10000000008',
    bvn: '20000000008',
    guarantorFullName: 'Amina Yusuf',
    guarantorEmail: 'amina.yusuf@example.com',
    guarantorPhoneNumber: '+2348090000008',
    guarantorCity: 'Kaduna',
    guarantorState: 'Kaduna',
    guarantorAddress: '7 Isa Kaita Road, Kaduna',
    verificationStatus: VerificationStatus.APPROVED,
  },

  // ---------- Pending verification (8) ----------
  {
    firstName: 'Segun',
    lastName: 'Balogun',
    email: 'segun.balogun@betawork.app',
    phoneNumber: '+2348030000009',
    city: 'Ilorin',
    state: 'Kwara',
    address: '11 Taiwo Road, Ilorin',
    businessName: 'Balogun Cooling Systems',
    trade: 'AC Technician',
    bio: 'Air-conditioning technician handling installation, servicing and gas refills.',
    yearsOfExperience: 5,
    serviceRadiusKm: 18,
    nin: '10000000009',
    bvn: '20000000009',
    guarantorFullName: 'Kola Balogun',
    guarantorEmail: 'kola.balogun@example.com',
    guarantorPhoneNumber: '+2348090000009',
    guarantorCity: 'Ilorin',
    guarantorState: 'Kwara',
    guarantorAddress: '4 Fate Road, Ilorin',
    verificationStatus: VerificationStatus.PENDING,
  },
  {
    firstName: 'Blessing',
    lastName: 'Okoro',
    email: 'blessing.okoro@betawork.app',
    phoneNumber: '+2348030000010',
    city: 'Owerri',
    state: 'Imo',
    address: '25 Wetheral Road, Owerri',
    businessName: 'Blessing Catering Services',
    trade: 'Caterer',
    bio: 'Event caterer serving weddings, corporate functions and private parties.',
    yearsOfExperience: 4,
    serviceRadiusKm: 50,
    nin: '10000000010',
    bvn: '20000000010',
    guarantorFullName: 'Grace Okoro',
    guarantorEmail: 'grace.okoro@example.com',
    guarantorPhoneNumber: '+2348090000010',
    guarantorCity: 'Owerri',
    guarantorState: 'Imo',
    guarantorAddress: '9 Douglas Road, Owerri',
    verificationStatus: VerificationStatus.PENDING,
  },
  {
    firstName: 'Yakubu',
    lastName: 'Danladi',
    email: 'yakubu.danladi@betawork.app',
    phoneNumber: '+2348030000011',
    city: 'Jos',
    state: 'Plateau',
    address: '2 Ahmadu Bello Way, Jos',
    businessName: 'Danladi Welding Works',
    trade: 'Welder',
    bio: 'Metal fabricator and welder producing gates, railings and structural steel.',
    yearsOfExperience: 13,
    serviceRadiusKm: 33,
    nin: '10000000011',
    bvn: '20000000011',
    guarantorFullName: 'Musa Danladi',
    guarantorEmail: 'musa.danladi@example.com',
    guarantorPhoneNumber: '+2348090000011',
    guarantorCity: 'Jos',
    guarantorState: 'Plateau',
    guarantorAddress: '16 Rukuba Road, Jos',
    verificationStatus: VerificationStatus.PENDING,
  },
  {
    firstName: 'Chioma',
    lastName: 'Nnaji',
    email: 'chioma.nnaji@betawork.app',
    phoneNumber: '+2348030000012',
    city: 'Awka',
    state: 'Anambra',
    address: '14 Zik Avenue, Awka',
    businessName: 'Chioma Cleaning Crew',
    trade: 'Cleaner',
    bio: 'Residential and post-construction cleaning with a trained, insured team.',
    yearsOfExperience: 3,
    serviceRadiusKm: 20,
    nin: '10000000012',
    bvn: '20000000012',
    guarantorFullName: 'Ada Nnaji',
    guarantorEmail: 'ada.nnaji@example.com',
    guarantorPhoneNumber: '+2348090000012',
    guarantorCity: 'Awka',
    guarantorState: 'Anambra',
    guarantorAddress: '6 Arthur Eze Avenue, Awka',
    verificationStatus: VerificationStatus.PENDING,
  },
  {
    firstName: 'Musa',
    lastName: 'Abubakar',
    email: 'musa.abubakar@betawork.app',
    phoneNumber: '+2348030000013',
    city: 'Maiduguri',
    state: 'Borno',
    address: '8 Baga Road, Maiduguri',
    businessName: 'Abubakar Solar Solutions',
    trade: 'Solar Installer',
    bio: 'Solar and inverter installer helping homes and shops stay powered.',
    yearsOfExperience: 6,
    serviceRadiusKm: 45,
    nin: '10000000013',
    bvn: '20000000013',
    guarantorFullName: 'Ali Abubakar',
    guarantorEmail: 'ali.abubakar@example.com',
    guarantorPhoneNumber: '+2348090000013',
    guarantorCity: 'Maiduguri',
    guarantorState: 'Borno',
    guarantorAddress: '3 Shehu Laminu Way, Maiduguri',
    verificationStatus: VerificationStatus.PENDING,
  },
  {
    firstName: 'Grace',
    lastName: 'Effiong',
    email: 'grace.effiong@betawork.app',
    phoneNumber: '+2348030000014',
    city: 'Uyo',
    state: 'Akwa Ibom',
    address: '19 Oron Road, Uyo',
    businessName: 'Grace Event Decor',
    trade: 'Event Decorator',
    bio: 'Event decorator crafting elegant setups for ceremonies and receptions.',
    yearsOfExperience: 5,
    serviceRadiusKm: 38,
    nin: '10000000014',
    bvn: '20000000014',
    guarantorFullName: 'Idara Effiong',
    guarantorEmail: 'idara.effiong@example.com',
    guarantorPhoneNumber: '+2348090000014',
    guarantorCity: 'Uyo',
    guarantorState: 'Akwa Ibom',
    guarantorAddress: '5 Aka Road, Uyo',
    verificationStatus: VerificationStatus.PENDING,
  },
  {
    firstName: 'Abdul',
    lastName: 'Suleiman',
    email: 'abdul.suleiman@betawork.app',
    phoneNumber: '+2348030000015',
    city: 'Sokoto',
    state: 'Sokoto',
    address: '7 Sultan Abubakar Road, Sokoto',
    businessName: 'Suleiman POP & Ceilings',
    trade: 'POP Installer',
    bio: 'Plaster-of-Paris and ceiling specialist for modern interior finishes.',
    yearsOfExperience: 7,
    serviceRadiusKm: 24,
    nin: '10000000015',
    bvn: '20000000015',
    guarantorFullName: 'Bashir Suleiman',
    guarantorEmail: 'bashir.suleiman@example.com',
    guarantorPhoneNumber: '+2348090000015',
    guarantorCity: 'Sokoto',
    guarantorState: 'Sokoto',
    guarantorAddress: '12 Kano Road, Sokoto',
    verificationStatus: VerificationStatus.PENDING,
  },
  {
    firstName: 'Peace',
    lastName: 'Adamu',
    email: 'peace.adamu@betawork.app',
    phoneNumber: '+2348030000016',
    city: 'Benin City',
    state: 'Edo',
    address: '22 Sapele Road, Benin City',
    businessName: 'Peace Phone Repairs',
    trade: 'Phone Repair Technician',
    bio: 'Mobile-device repair technician fixing screens, boards and batteries.',
    yearsOfExperience: 4,
    serviceRadiusKm: 16,
    nin: '10000000016',
    bvn: '20000000016',
    guarantorFullName: 'John Adamu',
    guarantorEmail: 'john.adamu@example.com',
    guarantorPhoneNumber: '+2348090000016',
    guarantorCity: 'Benin City',
    guarantorState: 'Edo',
    guarantorAddress: '4 Airport Road, Benin City',
    verificationStatus: VerificationStatus.PENDING,
  },
]

export default class extends BaseSeeder {
  async run() {
    // The admin acts as the verifier for approved artisans. Reuse the one the
    // admin seeder creates, or create it here so this seeder can run alone.
    const admin = await User.updateOrCreate(
      { email: 'admin@betawork.app' },
      {
        firstName: 'BetaWork',
        lastName: 'Admin',
        email: 'admin@betawork.app',
        phoneNumber: '+10000000000',
        password: PASSWORD,
        role: UserRole.ADMIN,
      }
    )

    for (const data of ARTISANS) {
      const user = await User.updateOrCreate(
        { email: data.email },
        {
          firstName: data.firstName,
          lastName: data.lastName,
          email: data.email,
          phoneNumber: data.phoneNumber,
          password: PASSWORD,
          city: data.city,
          state: data.state,
          address: data.address,
          role: UserRole.ARTISAN,
        }
      )

      const isApproved = data.verificationStatus === VerificationStatus.APPROVED

      await ArtisanProfile.updateOrCreate(
        { userId: user.id },
        {
          userId: user.id,
          businessName: data.businessName,
          trade: data.trade,
          bio: data.bio,
          yearsOfExperience: data.yearsOfExperience,
          city: data.city,
          state: data.state,
          address: data.address,
          serviceRadiusKm: data.serviceRadiusKm,
          isAvailable: true,
          nin: data.nin,
          bvn: data.bvn,
          photoUrl: `https://i.pravatar.cc/300?u=${encodeURIComponent(data.email)}`,
          guarantorFullName: data.guarantorFullName,
          guarantorEmail: data.guarantorEmail,
          guarantorPhoneNumber: data.guarantorPhoneNumber,
          guarantorCity: data.guarantorCity,
          guarantorState: data.guarantorState,
          guarantorAddress: data.guarantorAddress,
          verificationStatus: data.verificationStatus,
          verificationDocumentUrl: `https://example.com/verification/${data.nin}.pdf`,
          verificationNotes: isApproved ? 'Documents verified and approved.' : null,
          verifiedAt: isApproved ? DateTime.now() : null,
          verifiedBy: isApproved ? admin.id : null,
        }
      )
    }
  }
}
